apiVersion: v1
kind: Service
metadata:
  name: planora-server-service

spec:
  type: LoadBalancer   # exposes to internet

  selector:
    app: server

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000